### ISSUE TITLE
留档文件包含留档作者的nga账号

### ISSUE THREAD

**Issue by RichardGuyNotFavMHY** [soyussleet/NGA_AutoSave_Public#2]
留档文件包含留档作者的nga账号，这将对留档者的账号安全造成一定的影响(尤其是在分享数据库的过程中)。

**Comment by soyussleet** [comment]
可否详细说明一下？

**Comment by RichardGuyNotFavMHY** [comment]
就是，保存的页面右上角有保存账号的id。在分享数据库的时候这个id可能会暴露留档人的信息。

**Comment by soyussleet** [comment]
已收到问题报告，后续会更新

**Comment by soyussleet** [comment]
> 就是，保存的页面右上角有保存账号的id。在分享数据库的时候这个id可能会暴露留档人的信息。
保存网页的相关代码在DownloadMonitoringPages.py里，你可以自行查看然后修改，因为我在做新东西的开发所以没太有心思弄维护awa

**Comment by Kooluve** [comment]
这个问题对于分享文件挺关键的，此外网页源代码能搜到多处用户名和id的元素，希望能彻底改改
